In [1]:
import torch

In [3]:
scalar = torch.tensor(5)

In [5]:
scalar, scalar.ndim, scalar.item()

(tensor(5), 0, 5)

In [8]:
vector = torch.tensor([2,5])

In [11]:
vector, vector.ndim, vector.shape

(tensor([2, 5]), 1, torch.Size([2]))

In [12]:
matrix = torch.tensor([[1,3],[3,6]])

In [13]:
matrix

tensor([[1, 3],
        [3, 6]])

In [14]:
matrix, matrix.ndim, matrix.shape

(tensor([[1, 3],
         [3, 6]]),
 2,
 torch.Size([2, 2]))

In [15]:
matrix[0]

tensor([1, 3])

In [16]:
matrix[1][1]

tensor(6)

In [17]:
# Tensor
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [18]:
tensor, tensor.ndim, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [20]:
tensor[0][1:]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [21]:
tensor[0][0]

tensor([1, 2, 3])

In [22]:
tensor.ndim

3

In [29]:
# Random tensor
random_tensor = torch.rand(5,4,3)

In [30]:
random_tensor

tensor([[[0.1425, 0.1347, 0.7039],
         [0.9023, 0.8071, 0.8129],
         [0.5772, 0.5066, 0.6701],
         [0.3023, 0.4903, 0.6052]],

        [[0.8038, 0.3889, 0.2755],
         [0.8437, 0.0332, 0.1932],
         [0.4186, 0.0378, 0.9136],
         [0.8206, 0.5584, 0.8564]],

        [[0.2786, 0.6281, 0.2134],
         [0.4992, 0.5167, 0.8319],
         [0.0430, 0.6679, 0.4503],
         [0.1531, 0.0902, 0.4560]],

        [[0.9324, 0.9916, 0.2924],
         [0.9985, 0.1433, 0.1193],
         [0.3425, 0.4822, 0.0596],
         [0.9721, 0.9152, 0.7262]],

        [[0.7421, 0.1986, 0.4973],
         [0.9285, 0.0996, 0.5082],
         [0.1404, 0.7532, 0.6893],
         [0.2712, 0.1529, 0.8688]]])

In [31]:
random_tensor.ndim, random_tensor.shape

(3, torch.Size([5, 4, 3]))

In [32]:
image_size_tensor = torch.rand(224,224,3)

In [33]:
image_size = torch.rand(size=(224,224,3))

In [34]:
image_size

tensor([[[0.2046, 0.0107, 0.2541],
         [0.7870, 0.9101, 0.3372],
         [0.3522, 0.6685, 0.4835],
         ...,
         [0.6272, 0.5206, 0.3532],
         [0.9383, 0.2155, 0.7100],
         [0.9861, 0.6988, 0.9855]],

        [[0.2089, 0.8667, 0.8302],
         [0.9906, 0.8911, 0.6743],
         [0.0229, 0.9161, 0.6149],
         ...,
         [0.5997, 0.7136, 0.2815],
         [0.0881, 0.6443, 0.4864],
         [0.4971, 0.7403, 0.1944]],

        [[0.6521, 0.6435, 0.6986],
         [0.0774, 0.1190, 0.6276],
         [0.3101, 0.4215, 0.4547],
         ...,
         [0.6686, 0.8712, 0.6031],
         [0.3552, 0.4153, 0.8190],
         [0.2147, 0.2507, 0.8739]],

        ...,

        [[0.4572, 0.5857, 0.9071],
         [0.1622, 0.1084, 0.9251],
         [0.4719, 0.9807, 0.6394],
         ...,
         [0.5817, 0.4757, 0.2426],
         [0.9509, 0.0599, 0.0842],
         [0.0452, 0.9453, 0.1605]],

        [[0.8120, 0.9002, 0.1590],
         [0.3539, 0.4992, 0.5298],
         [0.

In [35]:
zeros = torch.zeros(size=(3,4))

In [36]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
zeros*image_size

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 2

In [39]:
ones = torch.ones(size=(3,4))

In [40]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [44]:
# Range
a = torch.arange(0,100,10)

In [45]:
a

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
torch.__version__

'2.8.0+cu126'

In [47]:
# torch like
ten_likes = torch.zeros_like(input=a)

In [48]:
ten_likes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Dtype, Device, Shape

In [56]:
# Dtypes
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float32)

In [57]:
float_32_tensor

tensor([3., 6., 9.])

In [58]:
float_32_tensor.dtype

torch.float32

In [60]:
# information from tensor
float_32_tensor.size()

torch.Size([3])

In [61]:
# Manipulation

In [62]:
a

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
a+10

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [64]:
b=(a+10)-3

In [65]:
b

tensor([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [66]:
c = torch.rand(2,6)

In [67]:
c, c+10

(tensor([[0.5237, 0.7134, 0.1723, 0.4383, 0.2368, 0.1204],
         [0.9115, 0.4024, 0.4705, 0.3411, 0.7202, 0.1263]]),
 tensor([[10.5237, 10.7134, 10.1723, 10.4383, 10.2368, 10.1204],
         [10.9115, 10.4024, 10.4705, 10.3411, 10.7202, 10.1263]]))

In [68]:
c, c*2

(tensor([[0.5237, 0.7134, 0.1723, 0.4383, 0.2368, 0.1204],
         [0.9115, 0.4024, 0.4705, 0.3411, 0.7202, 0.1263]]),
 tensor([[1.0475, 1.4268, 0.3445, 0.8765, 0.4736, 0.2409],
         [1.8229, 0.8047, 0.9410, 0.6822, 1.4404, 0.2526]]))

In [69]:
torch.mul(c,10)

tensor([[5.2373, 7.1339, 1.7226, 4.3825, 2.3680, 1.2043],
        [9.1147, 4.0237, 4.7052, 3.4111, 7.2020, 1.2630]])

In [70]:
# Matrix multiplication

mat23 = torch.tensor([[1,2,3],[4,5,6]])


In [71]:
mat23

tensor([[1, 2, 3],
        [4, 5, 6]])

In [72]:
mat33 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
mat33

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
mat23_final = torch.matmul(mat23, mat33)
mat23_final

tensor([[30, 36, 42],
        [66, 81, 96]])

In [79]:
mat23.shape, mat33.shape, mat23_final.shape

(torch.Size([2, 3]), torch.Size([3, 3]), torch.Size([2, 3]))